#!/usr/bin/env bash

set -eoi pipefail

docker build -t vibe-server:latest -f vibe-server/Dockerfile .
docker tag vibe-server:latest gcr.io/willyouplease-me/vibe-server:latest
docker push gcr.io/willyouplease-me/vibe-server:latest
# This one is deployed on GCloud compute which *should* pull the new image but might not.
